### ISSUE TITLE
Programmatic errors in mattermost messages

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-deployment-agent#118]
![image](https://user-images.githubusercontent.com/32402063/202726088-b1f35fad-3010-435a-bc13-aea0bb839e57.png)

Based on the message, it seems a programmatic error to me. It might help checking for out-of-range or None before creating the messages

**Comment by mrnicegyu11** [comment]
The second error mentioned here occurs on versions <0.10.3 when:
- a watched repo has `pull_only_files` enabled
- the watched repo watches git-tags

Fix: https://github.com/ITISFoundation/osparc-deployment-agent/pull/121

**Comment by pcrespov** [comment]
looking at the code, i am not sure how this relates... :0( but I understand this is still opened, right?

**Comment by mrnicegyu11** [comment]
This has been fixed in the `v0.10.4` release of the deployment agent, which should now run on all deployments.
Thanks for opening this issue :)

Closing...
