### ISSUE TITLE
Bug Aftermath: Add integration test for pulling latest docker image

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-deployment-agent#143]
We have run into a critical bug where it seems that new versions of portainer upon a REST POST/PUT request will (in contrary to old versions) not query if the `:latest` image on dockerhub has changed and potentially not pull the latest image.

This breaks the current osparc-simcore release workflow.

We shall add an integration test for all supported portainer versions which assesses that, if the sha of the latest image on dockerhub changed, a REST POST/PUT request to update stacks specifiying the `latest` image will update to the new version of the docker image. This should be akin to enabling this `Pull latest image version` flag in the portainer GUI upon updating services:
![image](https://user-images.githubusercontent.com/8209087/217907977-8bb45afe-6eb2-4666-90ff-3dd989d658d4.png)

CC @pcrespov

**Comment by pcrespov** [comment]
@mrnicegyu11 there is a new version of partinaer released in https://github.com/portainer/portainer/releases/tag/2.17.0

**Comment by pcrespov** [comment]
Perhaps temporary we could downgrade until this issue is resolved?
