### ISSUE TITLE
Retry deployment when "out of sequence" error happens

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-deployment-agent#2]
sometimes if the update is called while portainer is busy such an error arise.
using 'tenacity' to have a base retry on error would help a lot here.

**Comment by mrnicegyu11** [comment]
This is taken care of in the pending PR, see https://github.com/ITISFoundation/osparc-deployment-agent/pull/3/files#diff-b7b7f90ab5551420c80d89281609a67f392737cc90d34807d9ec13a13080011c
